#!/usr/bin/env bash

# Get Path to script folder
DIR="$( cd "$( dirname "$0" )" && pwd )"
# Fix path in case of symlinks
DIR=$(cd "$DIR" && pwd -P)

# Check for .dotfiles file and add symlink
dotfiles="$HOME/.dotfiles"
if [ -L $dotfiles ]; then
	echo "Removing existing $dotfiles symlink"
	rm $dotfiles
fi
if [ -d $dotfiles ]; then
	echo "Found existing $dotfiles folder. Skipping directory."
else
	echo "Linking $DIR => $dotfiles"
	ln -s "$DIR" "$dotfiles"
fi

# Recursively map dotfiles to home directory
echo "Installing individual dotfiles..."
while IFS= read -d $'\0' -r file ; do
	b=$(basename $file)
	c="$HOME/$b"
	d="$file"
	if [ -L $c ]; then
		rm $c
	fi
	if [ -f $c ]; then
		echo -e "Kept existing:\t$d"
	else
		ln -s "$d" "$c"
		echo -e "Link created:\t$d"
	fi
done < <(find "$DIR" -type f \( -iname ".*" ! -iname ".git" ! -iname ".gitmodules" ! -iname "*.swp" \) -print0)

# Throw in a .localrc if needed
if [ ! -e $HOME/.localrc ]; then
	echo -e "# This is your own .localrc file for your SUPER SECRET STUFF" > $HOME/.localrc
fi

# Install Oh My Zsh if not already installed
if [ ! -d "$HOME/.oh-my-zsh" ]; then
	echo "Installing Oh My Zsh..."
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
fi

# Remind user to open a new terminal
echo "Done! Open a new terminal (zsh) to load your config."

if [ ! -f "$HOME/.vim/autoload/plug.vim" ]; then
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
	git clone https://github.com/tmux-plugins/tpm "$HOME/.tmux/plugins/tpm"
	if ! { [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; } then
		tmux source-file "$HOME/.tmux.conf"
	fi
fi

# Install Homebrew if not already installed
if ! command -v brew &> /dev/null; then
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi
brew install wget curl
#curl -s 'https://api.macapps.link/en/firefox-chrome-evernote-dropbox-alfred-hyperswitch-fantastical-sublime-pycharm-dash-vscode-docker-insomnia-phpstorm-bbedit-iterm-unarchiver-filezilla-fluid-teamviewer-caffeine-flux-cloudapp-spectacle-vlc-adium-slack' | sh